apiVersion: apps/v1
kind: Deployment
metadata:
  name: orc-react-fe-k8s-lb
  labels:
    app: orc-react-fe-k8s-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orc-react-fe-k8s-lb
  template:
    metadata:
      labels:
        app: orc-react-fe-k8s-lb
    spec:
      containers:
        - name: orc-react-fe-k8s-lb
          image: shanehowl/orcmovielisting:latestv1
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: '128Mi'
              cpu: '200m'
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: orc-react-fe-k8s-lb
  labels:
    app: orc-react-fe-k8s-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: orc-react-fe-k8s-lb
