apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesapp
  labels:
    app: kubernetesapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetesapp
  template:
    metadata:
      labels:
        app: kubernetesapp
    spec:
      containers:
        - name: kubernetesapp
          image: femovielisting/ocikubernetesapp:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetesapp
  labels:
    app: kubernetesapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: kubernetesapp
